# this is a comment
[normalization]
name = "normalization"
kshape = [1,2,34]
bshape = [0]

[conv2d]
name = "conv2d"
kshape = [4, 5, 6]
bshape = [2, 1, 3, 7, 8, 9]

[conv2d_1]
name = "conv2d_1"
kshape = [4, 5, 6]
bshape = [2, 1, 3, 7, 8, 9]

[dense]
name = "dense"
kshape = [7,8,9,0]
bshape = [10,11,12,0]

[dense_1]
name = "dense_1"
kshape = [7,8,9,0]
bshape = [10,11,12,0]
